title: Richard Startin's Blog
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-twitter-plugin
permalink: /posts/:title
google_analytics: UA-107180613-2

twitter_username: richardstartin
github_username:  richardstartin

markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

share-links-active:
  twitter: true

navbar-links:
  About: "about"
  multi-matcher: /multi-matcher/

header_pages: 
  - about.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: /assets/images/penrose.png
collections:
    posts:
        output: true
