title: Richard Startin's Blog
theme: jekyll-theme-slate
permalink: /:title
google_analytics: UA-107180613-2

twitter_username: richardstartin
github_username:  richardstartin

collections:
    posts:
        output: true
