title: Richard Startin's Blog
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-redirect-from
permalink: /posts/:title
google_analytics: UA-107180613-2

twitter_username: richardstartin
github_username:  richardstartin

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: /assets/images/penrose.png
      redirect_from:
        - /:title/
collections:
    posts:
        output: true
